from typing import List
from ....models.outputs import FileArtifact
from ...validators.tsx_validator import TsxValidator


def generate_config_files() -> List[FileArtifact]:
    configs = []

    configs.append(FileArtifact(
        path="frontend/package.json",
        content="""{
  "name": "genesis-generated-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.0"
  }
}
""",
    ))

    configs.append(FileArtifact(
        path="frontend/tsconfig.json",
        content="""{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",
    ))

    configs.append(FileArtifact(
        path="frontend/next.config.js",
        content="""/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
""",
    ))

    configs.append(FileArtifact(
        path="frontend/postcss.config.js",
        content="""module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
""",
    ))

    configs.append(FileArtifact(
        path="frontend/tailwind.config.ts",
        content="""import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
""",
    ))

    layout_code = """import type { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Genesis App',
  description: 'Generated by Genesis Engine',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
"""
    is_valid, err_msg = TsxValidator.validate(layout_code, filename="frontend/app/layout.tsx")
    if not is_valid:
        raise ValueError(f"Generation Error (NextJsMinimalGenerator): {err_msg}")
    configs.append(FileArtifact(path="frontend/app/layout.tsx", content=layout_code))

    configs.append(FileArtifact(
        path="frontend/app/globals.css",
        content="""@tailwind base;
@tailwind components;
@tailwind utilities;

/* Genesis App - Generated Styles */

*, *::before, *::after {
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
  background: #f8f9fa;
  color: #1a1a2e;
  margin: 0;
  padding: 0;
}

.page-container {
  max-width: 960px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

.page-title {
  font-size: 1.75rem;
  font-weight: 700;
  margin: 0 0 1.5rem;
  color: #1a1a2e;
  border-bottom: 2px solid #e2e8f0;
  padding-bottom: 0.75rem;
}

.loading-text {
  color: #64748b;
  font-style: italic;
  margin: 1rem 0;
}

.error-banner {
  background: #fef2f2;
  color: #dc2626;
  border: 1px solid #fecaca;
  border-radius: 6px;
  padding: 0.75rem 1rem;
  margin: 0.75rem 0;
}

.entity-form {
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 1.25rem;
  margin-bottom: 1.5rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  align-items: flex-end;
}

.form-input {
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  padding: 0.5rem 0.75rem;
  font-size: 0.9rem;
  outline: none;
  transition: border-color 0.15s;
  min-width: 140px;
}

.form-input:focus {
  border-color: #6366f1;
  box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.15);
}

.form-label {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.9rem;
  color: #374151;
  cursor: pointer;
}

.btn {
  padding: 0.5rem 1rem;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  border: none;
  cursor: pointer;
  transition: opacity 0.15s;
  white-space: nowrap;
}

.btn:hover {
  opacity: 0.85;
}

.btn-primary {
  background: #6366f1;
  color: #ffffff;
}

.btn-secondary {
  background: #e2e8f0;
  color: #374151;
}

.btn-danger {
  background: #ef4444;
  color: #ffffff;
}

.btn-sm {
  padding: 0.3rem 0.65rem;
  font-size: 0.8rem;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  overflow: hidden;
}

.data-table th {
  background: #f1f5f9;
  color: #475569;
  font-weight: 600;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 0.65rem 0.875rem;
  text-align: left;
  border-bottom: 1px solid #e2e8f0;
}

.data-table td {
  padding: 0.65rem 0.875rem;
  border-bottom: 1px solid #f1f5f9;
  font-size: 0.9rem;
  color: #374151;
}

.data-table tr:last-child td {
  border-bottom: none;
}

.data-table tr:hover td {
  background: #f8fafc;
}

.table-actions {
  display: flex;
  gap: 0.5rem;
}

.empty-state {
  text-align: center;
  color: #94a3b8;
  font-size: 0.95rem;
  padding: 2rem;
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  margin-top: 0.75rem;
}
""",
    ))

    configs.append(FileArtifact(
        path="frontend/.gitignore",
        content="""node_modules/
.next/
out/
.env*.local
""",
    ))

    configs.append(FileArtifact(
        path="frontend/.env.example",
        content="NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8010\n",
    ))

    return configs
