from typing import List
from ....models.outputs import FileArtifact
from ...validators.tsx_validator import TsxValidator


def generate_config_files() -> List[FileArtifact]:
    configs = []

    configs.append(FileArtifact(
        path="frontend/package.json",
        content="""{
  "name": "genesis-generated-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.0"
  }
}
""",
    ))

    configs.append(FileArtifact(
        path="frontend/tsconfig.json",
        content="""{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",
    ))

    configs.append(FileArtifact(
        path="frontend/next.config.js",
        content="""/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
""",
    ))

    configs.append(FileArtifact(
        path="frontend/postcss.config.js",
        content="""module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
""",
    ))

    configs.append(FileArtifact(
        path="frontend/tailwind.config.ts",
        content="""import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
""",
    ))

    layout_code = """import type { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Genesis App',
  description: 'Generated by Genesis Engine',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
"""
    is_valid, err_msg = TsxValidator.validate(layout_code, filename="frontend/app/layout.tsx")
    if not is_valid:
        raise ValueError(f"Generation Error (NextJsMinimalGenerator): {err_msg}")
    configs.append(FileArtifact(path="frontend/app/layout.tsx", content=layout_code))

    configs.append(FileArtifact(
        path="frontend/app/globals.css",
        content="""@tailwind base;
@tailwind components;
@tailwind utilities;
""",
    ))

    configs.append(FileArtifact(
        path="frontend/.gitignore",
        content="""node_modules/
.next/
out/
.env*.local
""",
    ))

    configs.append(FileArtifact(
        path="frontend/.env.example",
        content="NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8010\n",
    ))

    return configs
