import json
from pydantic import BaseModel, Field
from typing import List, Dict
from ...core.workspace import WorkspaceManager
from ..state import ProjectState
from ..llm import get_llm
from langchain_core.prompts import ChatPromptTemplate

class ArchitectureOutput(BaseModel):
    folder_structure: Dict[str, str] = Field(description="Dictionary representing the root folders and their purposes")
    api_strategy: str = Field(description="Description of how the frontend and backend will communicate")
    database_schema: List[str] = Field(description="List of key database tables and relationships")

def system_architect_node(state: ProjectState) -> dict:
    project_id = state.get("project_id", "")
    print(f"[SystemArchitect] Designing architecture for Project {project_id}...")
    
    # Consume the specification generated by the RequirementAnalyzer, NOT the prompt
    specification = state.get("specification")
    if not specification:
        return {"errors": ["SystemArchitect failed: No ProjectSpecification found in state."]}
    
    llm = get_llm()
    structured_llm = llm.with_structured_output(ArchitectureOutput)
    
    system_prompt = """
    You are a Senior System Architect.
    Based strictly on the provided ProjectSpecification, design the high-level technical architecture.
    Return a suggested folder structure, the API communication strategy, and the key database tables needed.
    Do not invent requirements that are not in the specification.
    """
    
    chat_prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "Project Specification: {specification}")
    ])
    
    try:
        # Convert the spec dict to string for the prompt
        spec_str = json.dumps(specification, indent=2)
        result: ArchitectureOutput = (chat_prompt | structured_llm).invoke({"specification": spec_str})
        arch_dict = result.model_dump()
        
        # Write artifact to the physical workspace
        if project_id:
            project_dir = WorkspaceManager.get_project_dir(project_id)
            arch_path = project_dir / "artifacts" / "architecture.json"
            
            with open(arch_path, "w") as f:
                json.dump(arch_dict, f, indent=4)
                
            artifact_entry = {"architecture.json": str(arch_path)}
        else:
            artifact_entry = {}
            
        return {
            "events": ["ArchitectureCompleted"],
            "artifacts": artifact_entry,
            "status": "ARCHITECTURE_COMPLETE"
        }
    except Exception as e:
        return {"errors": [f"SystemArchitect failed: {str(e)}"]}
