import json
from pydantic import BaseModel, Field
from typing import List, Dict
from ...core.workspace import WorkspaceManager
from ..state import ProjectState
from ..llm import get_llm
from langchain_core.prompts import ChatPromptTemplate


class ArchitectureOutput(BaseModel):
    folder_structure: Dict[str, str] = Field(description="Dictionary representing the root folders and their purposes")
    api_strategy: str = Field(description="Description of how the frontend and backend will communicate")
    database_schema: List[str] = Field(description="List of key database tables and relationships")


def system_architect_node(state: ProjectState) -> dict:
    """
    LangGraph node: Designs the high-level technical architecture from the ProjectSpecification.
    
    This node is production code. It does NOT perform disk I/O directly.
    It produces a domain result; the calling orchestrator is responsible for persistence.
    """
    project_id = state.get("project_id", "")

    # Consume the specification generated by the RequirementAnalyzer, NOT the prompt
    specification = state.get("specification")
    if not specification:
        return {"errors": ["SystemArchitect failed: No ProjectSpecification found in state."]}

    llm = get_llm()
    structured_llm = llm.with_structured_output(ArchitectureOutput)

    system_prompt = """
    You are a Senior System Architect.
    Based strictly on the provided ProjectSpecification, design the high-level technical architecture.
    Return a suggested folder structure, the API communication strategy, and the key database tables needed.
    Do not invent requirements that are not in the specification.
    """

    chat_prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "Project Specification: {specification}")
    ])

    try:
        spec_str = json.dumps(specification, indent=2)
        result: ArchitectureOutput = (chat_prompt | structured_llm).invoke({"specification": spec_str})
        arch_dict = result.model_dump()

        artifact_path = None
        if project_id:
            project_dir = WorkspaceManager.get_project_dir(project_id)
            artifact_path = str(project_dir / "artifacts" / "architecture.json")

        return {
            "events": ["ArchitectureCompleted"],
            "artifacts": {"architecture.json": artifact_path} if artifact_path else {},
            "status": "ARCHITECTURE_COMPLETE",
            "_persist_arch": {"path": artifact_path, "data": arch_dict} if artifact_path else None,
        }
    except Exception as e:
        return {"errors": [f"SystemArchitect failed: {str(e)}"]}
