from ...interfaces.plugin import GenerationPlugin
from ...models.outputs import FileArtifact
from ...rules.base import RuleContext
from ..validators.tsx_validator import TsxValidator
from typing import List

class NextJsPlugin(GenerationPlugin):
    @property
    def name(self): return "NextJsMinimalGenerator"
    @property
    def target_framework(self): return "nextjs"

    def _generate_config_files(self) -> List[FileArtifact]:
        configs = []

        configs.append(FileArtifact(
            path="frontend/package.json",
            content="""{
  "name": "genesis-generated-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.0"
  }
}
""",
        ))

        configs.append(FileArtifact(
            path="frontend/tsconfig.json",
            content="""{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",
        ))

        configs.append(FileArtifact(
            path="frontend/next.config.js",
            content="""/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
""",
        ))

        configs.append(FileArtifact(
            path="frontend/postcss.config.js",
            content="""module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
""",
        ))

        configs.append(FileArtifact(
            path="frontend/tailwind.config.ts",
            content="""import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
""",
        ))

        layout_code = """import type { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Genesis App',
  description: 'Generated by Genesis Engine',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
"""
        is_valid, err_msg = TsxValidator.validate(layout_code, filename="frontend/app/layout.tsx")
        if not is_valid:
            raise ValueError(f"Generation Error (NextJsMinimalGenerator): {err_msg}")
        configs.append(FileArtifact(path="frontend/app/layout.tsx", content=layout_code))

        configs.append(FileArtifact(
            path="frontend/app/globals.css",
            content="""@tailwind base;
@tailwind components;
@tailwind utilities;
""",
        ))

        configs.append(FileArtifact(
            path="frontend/.gitignore",
            content="""node_modules/
.next/
out/
.env*.local
""",
        ))

        return configs

    def generate(self, context: RuleContext) -> List[FileArtifact]:
        artifacts = self._generate_config_files()

        # Pages → frontend/app/{route}/page.tsx
        if context.page_graph:
            for page in context.page_graph.pages:
                clean_route = page.route.strip("/")
                path = f"frontend/app/{clean_route}/page.tsx" if clean_route else "frontend/app/page.tsx"
                comp_name = page.name.replace(" ", "")
                code = "\n".join([
                    f"export default function {comp_name}() {{",
                    f"    return (",
                    f"        <div>",
                    f"            <h1>{page.name}</h1>",
                    f"            <p>Generated deterministically by Genesis Engine.</p>",
                    f"        </div>",
                    f"    );",
                    f"}}",
                ])
                is_valid, err_msg = TsxValidator.validate(code, filename=path)
                if not is_valid:
                    raise ValueError(f"Generation Error (NextJsMinimalGenerator): {err_msg}")
                artifacts.append(FileArtifact(path=path, content=code))

        # Spec-declared components → frontend/components/{Name}.tsx
        if context.component_graph:
            spec_components = [
                c for c in context.component_graph.components
                if c.metadata.created_by == "SpecComponent"
            ]
            for comp in spec_components:
                path = f"frontend/components/{comp.name}.tsx"
                code = "\n".join([
                    f"export default function {comp.name}() {{",
                    f"    return (",
                    f"        <div>",
                    f"            <span>{comp.name}</span>",
                    f"        </div>",
                    f"    );",
                    f"}}",
                ])
                is_valid, err_msg = TsxValidator.validate(code, filename=path)
                if not is_valid:
                    raise ValueError(f"Generation Error (NextJsMinimalGenerator): {err_msg}")
                artifacts.append(FileArtifact(path=path, content=code))

        return artifacts
