def generate_router_code(table, plural: str) -> str:
    name = table.name
    lower = table.name.lower()
    model_alias = f"{name}Model"
    lines = [
        "from typing import List",
        "from fastapi import APIRouter, Depends, HTTPException",
        "from sqlalchemy.orm import Session",
        f"from ..schemas import {name}, {name}Create",
        "from ..database import get_db",
        f"from ..models import {name} as {model_alias}",
        "",
        "",
        f'router = APIRouter(prefix="/{plural}", tags=["{plural}"])',
        "",
        "",
        f'@router.get("/", response_model=List[{name}])',
        f"def list_{plural}(db: Session = Depends(get_db)):",
        f"    return db.query({model_alias}).all()",
        "",
        "",
        f'@router.get("/{{item_id}}", response_model={name})',
        f"def get_{lower}(item_id: int, db: Session = Depends(get_db)):",
        f"    record = db.query({model_alias}).filter({model_alias}.id == item_id).first()",
        "    if not record:",
        f'        raise HTTPException(status_code=404, detail="{lower} not found")',
        "    return record",
        "",
        "",
        f'@router.post("/", response_model={name}, status_code=201)',
        f"def create_{lower}(item: {name}Create, db: Session = Depends(get_db)):",
        f"    record = {model_alias}(**item.model_dump())",
        "    db.add(record)",
        "    db.commit()",
        "    db.refresh(record)",
        "    return record",
        "",
        "",
        f'@router.put("/{{item_id}}", response_model={name})',
        f"def update_{lower}(item_id: int, item: {name}Create, db: Session = Depends(get_db)):",
        f"    record = db.query({model_alias}).filter({model_alias}.id == item_id).first()",
        "    if not record:",
        f'        raise HTTPException(status_code=404, detail="{lower} not found")',
        "    for k, v in item.model_dump().items():",
        "        setattr(record, k, v)",
        "    db.commit()",
        "    db.refresh(record)",
        "    return record",
        "",
        "",
        f'@router.delete("/{{item_id}}", status_code=204)',
        f"def delete_{lower}(item_id: int, db: Session = Depends(get_db)):",
        f"    record = db.query({model_alias}).filter({model_alias}.id == item_id).first()",
        "    if not record:",
        f'        raise HTTPException(status_code=404, detail="{lower} not found")',
        "    db.delete(record)",
        "    db.commit()",
        "",
    ]
    return "\n".join(lines)
